### ISSUE TITLE
Uncaught Error: Call to undefined function Q() in /var/www/html/mailtest/plugins/calendar/calendar.php:565

### ISSUE THREAD

**Issue by Offerel** [fasterit/roundcube_calendar#15]
After enabling the Plugin in Roundcube 1.3.0 i get the following error, if i try to access the calendar settings in the setting area of  Roundcube:

`Fatal error: Uncaught Error: Call to undefined function Q() in /var/www/html/mailtest/plugins/calendar/calendar.php:565 Stack trace: #0 /var/www/html/mailtest/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->preferences_list(Array) #1 /var/www/rc-1.3.0/program/steps/settings/func.inc(1247): rcube_plugin_api->exec_hook('preferences_lis...', Array) #2 /var/www/rc-1.3.0/program/steps/settings/edit_prefs.inc(28): rcmail_user_prefs('calendar') #3 /var/www/rc-1.3.0/index.php(303): include_once('/var/www/rc-...') #4 {main} thrown in /var/www/html/mailtest/plugins/calendar/calendar.php on line 565`

**Comment by Offerel** [comment]
If i go directly to the calendar, i get:

`
Fatal error: Uncaught Error: Call to undefined function rcube_autocomplete_init() in /var/www/html/mailtest/plugins/calendar/calendar.php:498`

**Comment by Kallb123** [comment]
Same problems here, can't open the calendar or the settings. I get the same errors as above.

I guess no caldav in roundcube then if this plugin won't be updated? :(

**Comment by archont00** [comment]
Same here. Arch Linux, php 7.1.6, current stable roundcube.

**Comment by user7466** [comment]
It looks like the developer of the caldav patches that this project is forked from have made changes for roundcube 1.3.
https://gitlab.awesome-it.de/kolab/roundcube-plugins/commit/967eac96c7b898cf44ba7193815117fc2aac618d
Maybe those same changes will apply here.
I may find time to try it out in the next week if someone else does not first.

**Comment by archont00** [comment]
If you can, it would be nice.

**Comment by fasterit** [comment]
Yes, that is a Roundcube 1.3+ compatibility change that needs to be pulled in for people that want to run the version of Roundcube released 26.06.2017 (or presumably later version, too).
/DLange

**Comment by pafcioooo** [comment]
@Offerel can you put somewhere, working plugin with patches for 1.3 version. I need it for #21 .

**Comment by fasterit** [comment]
Check https://github.com/dotplex/roundcube_calendar/tree/62a76cfd8a6279ab69795fd73141da26a27126d0 . The patches seem to be in the repo there.
Leave some feedback how they work on a Roundcube 1.3.x.

**Comment by pafcioooo** [comment]
@fasterit thanks:-) It works. I will continue in #21 - feedback will be there too.
