### ISSUE TITLE
Calendar Plugin with direct access to SabreDAV DB possible?

### ISSUE THREAD

**Issue by Offerel** [fasterit/roundcube_calendar#16]
I don't know if this is a stupid idea, but i think it is...

Is it possible, that someone with enough knowledge could please develop a Calendar Plugin which does not sync via CalDAV, but instead uses the SabreDAV DB directly? Is this possible?

At least in my case, both (SabreDAV and Roundcube) uses the same DB Server on the same Machine. If i would rename all the tables and i change them to use some prefix, they could use also the same Database. So i think, such a combination could be a lot faster and more stable, as syncing via CalDAV.

**Comment by texxasrulez** [comment]
Anything is possible I have found. This particular version of calendar is meant for nextcloud use only. There are other forks out there that may be working on implementing something like you described
