### ISSUE TITLE
not working, roundcube 1.3.6, empty settings page and calendar page - using dotplex repository

### ISSUE THREAD

**Issue by yondermeister** [fasterit/roundcube_calendar#23]
After using this repo https://github.com/dotplex/roundcube_calendar (as it was referred to us in #21, I get this message (roundcube being in debug mode):

> Warning: require_once(/var/www/html/roundcube/plugins/calendar/drivers/**databse/databse_driver**.php): failed to open stream: Aucun fichier ou dossier de ce type in /var/www/html/roundcube/plugins/calendar/calendar.php on line 249
> 
> Fatal error: require_once(): Failed opening required '/var/www/html/roundcube/plugins/calendar/drivers/databse/databse_driver.php' (include_path='/var/www/html/roundcube/vendor/pear/auth_sasl:/var/www/html/roundcube/vendor/pear/console_commandline:/var/www/html/roundcube/vendor/pear/console_getopt:/var/www/html/roundcube/vendor/pear/crypt_gpg:/var/www/html/roundcube/vendor/pear/mail_mime:/var/www/html/roundcube/vendor/pear/net_idna2:/var/www/html/roundcube/vendor/pear/net_ldap2:/var/www/html/roundcube/vendor/pear/net_smtp:/var/www/html/roundcube/vendor/pear/net_socket:/var/www/html/roundcube/vendor/pear/pear-core-minimal/src:/var/www/html/roundcube/vendor/pear/pear_exception:/var/www/html/roundcube/program/lib:.:/usr/share/php') in /var/www/html/roundcube/plugins/calendar/calendar.php on line 249

I notice that there is a typo on **databse/databse_driver**. After checking the directory on my server, I read databAse/databAse_driver.
I am however unable to find any reference to this typo in the php file calendar.php line 249, as mentioned in the error message.

Could anyone point me to where this typo might actually be located, so I can correct it? I am not a programmer, so I don't know if line 249 is an indirect reference.
Thanks.

**Comment by pafcioooo** [comment]
I am not programmer either but checking my roundcube/plugins/calendar/calendar.php line 249 see that there is reference to variable $driver_name:
`require_once($this->home . '/drivers/' . $driver_name . '/' . $driver_class . '.php');`
I suppose it can have something in common with config parameter in plugin config file plugins/calendar/config.inc.php that in my case looks like this:
`$config['calendar_driver'] = array('database', 'caldav');`
I suppose you can have a typo there.

**Comment by yondermeister** [comment]
You are a lifesaver!
I have been looking around for two months. I have come to understand the meaning and implications of a 'repository' on github. I was so distracted by how stuck I had been, that I didn't think to check the driver setting in config.inc.php in /plugin/calendar.
Thank you!

**Comment by pafcioooo** [comment]
I am happy that I could help:-)

**Comment by pafcioooo** [comment]
@fasterit just BTW, why this repo cannot be merged https://github.com/dotplex/roundcube_calendar somehow?
